#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd /tmp

echo "Finding latest release..."
TAG=$(git ls-remote --tags --exit-code --refs https://github.com/AndrewVos/pj.git | sed -E 's/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/g' | tail -n1)
RELEASE_URL="https://github.com/AndrewVos/pj/releases/download/$TAG/pj-$TAG-linux-amd64.tar.gz"

echo "Downloading $RELEASE_URL..."
wget "$RELEASE_URL" --output-document pj.tar.gz --quiet

echo "Extracting..."
tar -zxvf pj.tar.gz > /dev/null

echo "Installing binary..."
if [[ -d /usr/local/bin ]]; then
  sudo mv pj /usr/local/bin/pj
fi

cd - > /dev/null
